[2024-09-09T18:06:36.179-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-09T18:06:36.190-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dat_dbt_raw_model.dat_dbt_raw_model scheduled__2024-08-20T08:15:00+00:00 [queued]>
[2024-09-09T18:06:36.198-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dat_dbt_raw_model.dat_dbt_raw_model scheduled__2024-08-20T08:15:00+00:00 [queued]>
[2024-09-09T18:06:36.199-0300] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-09T18:06:36.221-0300] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dat_dbt_raw_model> on 2024-08-20 08:15:00+00:00
[2024-09-09T18:06:36.224-0300] {standard_task_runner.py:72} INFO - Started process 169041 to run task
[2024-09-09T18:06:36.225-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dat_dbt_raw_model', 'dat_dbt_raw_model', 'scheduled__2024-08-20T08:15:00+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/dat_dbt_trusted_model.py', '--cfg-path', '/tmp/tmp5g2yykze']
[2024-09-09T18:06:36.227-0300] {standard_task_runner.py:105} INFO - Job 58: Subtask dat_dbt_raw_model
[2024-09-09T18:06:36.279-0300] {task_command.py:467} INFO - Running <TaskInstance: dat_dbt_raw_model.dat_dbt_raw_model scheduled__2024-08-20T08:15:00+00:00 [running]> on host DESKTOP-0CT35O1.
[2024-09-09T18:06:36.351-0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Matheus' AIRFLOW_CTX_DAG_ID='dat_dbt_raw_model' AIRFLOW_CTX_TASK_ID='dat_dbt_raw_model' AIRFLOW_CTX_EXECUTION_DATE='2024-08-20T08:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-20T08:15:00+00:00'
[2024-09-09T18:06:36.353-0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-09T18:06:36.354-0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-09T18:06:36.355-0300] {logging_mixin.py:190} INFO - Current task name:dat_dbt_raw_model state:running start_date:2024-09-09 21:06:36.191634+00:00
[2024-09-09T18:06:36.356-0300] {logging_mixin.py:190} INFO - Dag name:dat_dbt_raw_model and current dag run status:running
[2024-09-09T18:06:36.357-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-09T18:06:36.358-0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-09T18:06:36.360-0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/dbt_project/bancos_airflow && eval "\\$(pyenv init -)" && eval "\\$(pyenv virtualenv-init -)" && pyenv activate dbt_env && dbt run --models bancos_trusted']
[2024-09-09T18:06:36.364-0300] {subprocess.py:86} INFO - Output:
[2024-09-09T18:06:36.365-0300] {subprocess.py:93} INFO - /usr/bin/bash: line 1: cd: too many arguments
[2024-09-09T18:06:36.366-0300] {subprocess.py:97} INFO - Command exited with return code 1
[2024-09-09T18:06:36.375-0300] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-09-09T18:06:36.390-0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-09T18:06:36.391-0300] {logging_mixin.py:190} INFO - Task start:2024-09-09 21:06:36.191634+00:00 end:2024-09-09 21:06:36.389796+00:00 duration:0.198162
[2024-09-09T18:06:36.392-0300] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): dat_dbt_raw_model> dag:<DAG: dat_dbt_raw_model> dagrun:<DagRun dat_dbt_raw_model @ 2024-08-20 08:15:00+00:00: scheduled__2024-08-20T08:15:00+00:00, state:running, queued_at: 2024-09-09 21:06:21.862704+00:00. externally triggered: False>
[2024-09-09T18:06:36.393-0300] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 1.
[2024-09-09T18:06:36.394-0300] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dat_dbt_raw_model, task_id=dat_dbt_raw_model, run_id=scheduled__2024-08-20T08:15:00+00:00, execution_date=20240820T081500, start_date=20240909T210636, end_date=20240909T210636
[2024-09-09T18:06:36.424-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-09T18:06:36.425-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 58 for task dat_dbt_raw_model (Bash command failed. The command returned a non-zero exit code 1.; 169041)
Traceback (most recent call last):
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/teu20/Documents/Poli/Repo/eEDB011-20243/atividade 6 - WSL/airflow/airflow_env/lib/python3.10/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-09-09T18:06:36.479-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-09T18:06:36.493-0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-09T18:06:36.494-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
